
spring:
  application:
    name: OnlineStore
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/online-store}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


SECRET_KEY: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
