name: OnlineStore

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Set up MySQL
        uses: mysql/setup-mysql@v2
        with:
          mysql-version: '8.0'
          url: ${{ secrets.DB_URL }}
          password: ${{ secrets.DB_PASSWORD }}
          username: ${{ secrets.DB_USERNAME }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

