name: OnlineStore

on: [push]

env:
  MYSQL_DATABASE: online-store
  DB_USER: b08666f729d80e
  DB_PASSWORD: cb12eebb
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Set up MySQL
        with:
          mysql-version: '8.0'
          url: ${{ secrets.DB_URL }}
          password: ${{ env.DB_PASSWORD }}
          username: ${{ env.DB_USERNAME }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

